#!/bin/sh
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 --dec inner --enc gat --est nce --readout mean --sampler mvgrl --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 --dec bilinear --enc gat --est nce --readout mean --sampler mvgrl --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gat --est jsd --readout sum --sampler gca --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gat --est jsd --readout sum --sampler gca --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec inner --enc gin --est nce --readout sum --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec bilinear --enc gin --est nce --readout sum --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec inner --enc linear --est nce --readout mean --sampler node-rand_walk-random --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec bilinear --enc linear --est nce --readout mean --sampler node-rand_walk-random --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gcn --est jsd --readout mean --sampler node-neighbor-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gcn --est jsd --readout mean --sampler node-neighbor-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc linear --est nce --readout sum --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc linear --est nce --readout sum --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 --dec inner --enc gin --est jsd --readout mean --sampler mvgrl --dataset pubmed --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 --dec bilinear --enc gin --est jsd --readout mean --sampler mvgrl --dataset pubmed --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 --dec inner --enc none --est nce --readout mean --sampler node-rand_walk-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 --dec bilinear --enc none --est nce --readout mean --sampler node-rand_walk-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec inner --enc none --est jsd --readout mean --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec bilinear --enc none --est jsd --readout mean --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc gin --est jsd --readout sum --sampler dgi --dataset coauthor_phy --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc gin --est jsd --readout sum --sampler dgi --dataset coauthor_phy --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc linear --est jsd --readout mean --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc linear --est jsd --readout mean --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gat --est nce --readout mean --sampler mvgrl --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gat --est nce --readout mean --sampler mvgrl --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec inner --enc linear --est jsd --readout mean --sampler gca --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec bilinear --enc linear --est jsd --readout mean --sampler gca --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc gat --est nce --readout sum --sampler node-rand_walk-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc gat --est nce --readout sum --sampler node-rand_walk-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec inner --enc gat --est jsd --readout mean --sampler gca --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec bilinear --enc gat --est jsd --readout mean --sampler gca --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec inner --enc gcn --est nce --readout mean --sampler node-neighbor-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec bilinear --enc gcn --est nce --readout mean --sampler node-neighbor-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec inner --enc gin --est nce --readout sum --sampler mvgrl --dataset amazon_computers --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec bilinear --enc gin --est nce --readout sum --sampler mvgrl --dataset amazon_computers --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec inner --enc gat --est jsd --readout mean --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec bilinear --enc gat --est jsd --readout mean --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gat --est jsd --readout mean --sampler node-neighbor-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gat --est jsd --readout mean --sampler node-neighbor-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec inner --enc gat --est jsd --readout sum --sampler mvgrl --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec bilinear --enc gat --est jsd --readout sum --sampler mvgrl --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec inner --enc gat --est nce --readout mean --sampler mvgrl --dataset amazon_computers --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec bilinear --enc gat --est nce --readout mean --sampler mvgrl --dataset amazon_computers --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec inner --enc gat --est nce --readout sum --sampler node-neighbor-random --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gat --est nce --readout sum --sampler node-neighbor-random --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec inner --enc gcn --est nce --readout mean --sampler gca --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gcn --est nce --readout mean --sampler gca --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec inner --enc gin --est nce --readout mean --sampler node-rand_walk-random --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec bilinear --enc gin --est nce --readout mean --sampler node-rand_walk-random --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gat --est nce --readout sum --sampler gca --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gat --est nce --readout sum --sampler gca --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec inner --enc none --est nce --readout mean --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec bilinear --enc none --est nce --readout mean --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec inner --enc linear --est nce --readout sum --sampler node-rand_walk-random --dataset pubmed --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec bilinear --enc linear --est nce --readout sum --sampler node-rand_walk-random --dataset pubmed --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc linear --est nce --readout mean --sampler node-rand_walk-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc linear --est nce --readout mean --sampler node-rand_walk-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec inner --enc gin --est nce --readout sum --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gin --est nce --readout sum --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec inner --enc gat --est nce --readout mean --sampler aug --dataset pubmed --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec bilinear --enc gat --est nce --readout mean --sampler aug --dataset pubmed --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec inner --enc linear --est jsd --readout mean --sampler node-rand_walk-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec bilinear --enc linear --est jsd --readout mean --sampler node-rand_walk-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc linear --est nce --readout sum --sampler gca --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc linear --est nce --readout sum --sampler gca --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec inner --enc gin --est nce --readout sum --sampler node-rand_walk-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec bilinear --enc gin --est nce --readout sum --sampler node-rand_walk-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 --dec inner --enc gat --est nce --readout sum --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 --dec bilinear --enc gat --est nce --readout sum --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec inner --enc gat --est nce --readout sum --sampler aug --dataset amazon_computers --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec bilinear --enc gat --est nce --readout sum --sampler aug --dataset amazon_computers --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec inner --enc linear --est jsd --readout sum --sampler node-rand_walk-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec bilinear --enc linear --est jsd --readout sum --sampler node-rand_walk-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec inner --enc gin --est nce --readout sum --sampler node-rand_walk-random --dataset pubmed --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gin --est nce --readout sum --sampler node-rand_walk-random --dataset pubmed --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec inner --enc linear --est jsd --readout sum --sampler node-neighbor-random --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec bilinear --enc linear --est jsd --readout sum --sampler node-neighbor-random --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec inner --enc gin --est nce --readout sum --sampler gca --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec bilinear --enc gin --est nce --readout sum --sampler gca --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 --dec inner --enc gcn --est nce --readout sum --sampler mvgrl --dataset coauthor_cs --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 --dec bilinear --enc gcn --est nce --readout sum --sampler mvgrl --dataset coauthor_cs --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec inner --enc gcn --est jsd --readout sum --sampler aug --dataset pubmed --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gcn --est jsd --readout sum --sampler aug --dataset pubmed --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 --dec inner --enc gcn --est jsd --readout mean --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 --dec bilinear --enc gcn --est jsd --readout mean --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc linear --est nce --readout sum --sampler node-rand_walk-random --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc linear --est nce --readout sum --sampler node-rand_walk-random --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec inner --enc gin --est jsd --readout sum --sampler aug --dataset wikics --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec bilinear --enc gin --est jsd --readout sum --sampler aug --dataset wikics --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec inner --enc gat --est nce --readout mean --sampler node-rand_walk-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gat --est nce --readout mean --sampler node-rand_walk-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec inner --enc gcn --est jsd --readout sum --sampler gca --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gcn --est jsd --readout sum --sampler gca --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec inner --enc gcn --est jsd --readout sum --sampler aug --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec bilinear --enc gcn --est jsd --readout sum --sampler aug --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gat --est nce --readout sum --sampler node-rand_walk-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gat --est nce --readout sum --sampler node-rand_walk-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc gat --est jsd --readout mean --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc gat --est jsd --readout mean --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec inner --enc gat --est nce --readout mean --sampler node-neighbor-random --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gat --est nce --readout mean --sampler node-neighbor-random --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 --dec inner --enc gat --est nce --readout sum --sampler gca --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 --dec bilinear --enc gat --est nce --readout sum --sampler gca --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec inner --enc none --est jsd --readout mean --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec bilinear --enc none --est jsd --readout mean --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec inner --enc gin --est nce --readout mean --sampler aug --dataset citeseer --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec bilinear --enc gin --est nce --readout mean --sampler aug --dataset citeseer --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gcn --est jsd --readout sum --sampler mvgrl --dataset coauthor_phy --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gcn --est jsd --readout sum --sampler mvgrl --dataset coauthor_phy --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc gcn --est jsd --readout sum --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc gcn --est jsd --readout sum --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc linear --est nce --readout sum --sampler node-neighbor-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc linear --est nce --readout sum --sampler node-neighbor-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 --dec inner --enc gat --est jsd --readout mean --sampler node-neighbor-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 --dec bilinear --enc gat --est jsd --readout mean --sampler node-neighbor-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec inner --enc gcn --est jsd --readout mean --sampler node-rand_walk-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gcn --est jsd --readout mean --sampler node-rand_walk-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec inner --enc gcn --est nce --readout sum --sampler node-neighbor-random --dataset pubmed --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec bilinear --enc gcn --est nce --readout sum --sampler node-neighbor-random --dataset pubmed --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gcn --est nce --readout sum --sampler dgi --dataset pubmed --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gcn --est nce --readout sum --sampler dgi --dataset pubmed --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec inner --enc none --est jsd --readout mean --sampler node-neighbor-random --dataset pubmed --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec bilinear --enc none --est jsd --readout mean --sampler node-neighbor-random --dataset pubmed --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec inner --enc gcn --est nce --readout sum --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec bilinear --enc gcn --est nce --readout sum --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec inner --enc gcn --est nce --readout mean --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec bilinear --enc gcn --est nce --readout mean --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec inner --enc gcn --est nce --readout sum --sampler node-neighbor-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec bilinear --enc gcn --est nce --readout sum --sampler node-neighbor-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc none --est nce --readout mean --sampler gca --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc none --est nce --readout mean --sampler gca --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc gin --est nce --readout sum --sampler node-neighbor-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc gin --est nce --readout sum --sampler node-neighbor-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec inner --enc none --est jsd --readout mean --sampler gca --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec bilinear --enc none --est jsd --readout mean --sampler gca --dataset coauthor_cs --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec inner --enc gin --est nce --readout sum --sampler aug --dataset coauthor_phy --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec bilinear --enc gin --est nce --readout sum --sampler aug --dataset coauthor_phy --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gin --est jsd --readout sum --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec inner --enc gat --est jsd --readout mean --sampler aug --dataset coauthor_cs --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec bilinear --enc gat --est jsd --readout mean --sampler aug --dataset coauthor_cs --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec inner --enc gin --est nce --readout sum --sampler aug --dataset citeseer --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec bilinear --enc gin --est nce --readout sum --sampler aug --dataset citeseer --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 --dec inner --enc gat --est nce --readout mean --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 --dec bilinear --enc gat --est nce --readout mean --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec inner --enc gin --est nce --readout mean --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 --dec bilinear --enc gin --est nce --readout mean --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gin --est nce --readout mean --sampler dgi --dataset amazon_computers --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gin --est nce --readout mean --sampler dgi --dataset amazon_computers --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec inner --enc gcn --est nce --readout mean --sampler node-rand_walk-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec bilinear --enc gcn --est nce --readout mean --sampler node-rand_walk-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec inner --enc gat --est jsd --readout sum --sampler node-neighbor-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gat --est jsd --readout sum --sampler node-neighbor-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 --dec inner --enc gcn --est jsd --readout mean --sampler node-neighbor-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 --dec bilinear --enc gcn --est jsd --readout mean --sampler node-neighbor-random --dataset citeseer --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec inner --enc gat --est nce --readout sum --sampler aug --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec bilinear --enc gat --est nce --readout sum --sampler aug --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec inner --enc gat --est jsd --readout mean --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec bilinear --enc gat --est jsd --readout mean --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 --dec inner --enc gat --est nce --readout mean --sampler node-rand_walk-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 --dec bilinear --enc gat --est nce --readout mean --sampler node-rand_walk-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gcn --est nce --readout sum --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gcn --est nce --readout sum --sampler dgi --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec inner --enc gin --est nce --readout sum --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gin --est nce --readout sum --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec inner --enc gat --est jsd --readout mean --sampler aug --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec bilinear --enc gat --est jsd --readout mean --sampler aug --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc none --est jsd --readout mean --sampler node-neighbor-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc none --est jsd --readout mean --sampler node-neighbor-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec inner --enc gcn --est jsd --readout mean --sampler mvgrl --dataset wikics --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --dec bilinear --enc gcn --est jsd --readout mean --sampler mvgrl --dataset wikics --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec inner --enc none --est nce --readout sum --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec bilinear --enc none --est nce --readout sum --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 --dec inner --enc linear --est jsd --readout mean --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 --dec bilinear --enc linear --est jsd --readout mean --sampler node-rand_walk-random --dataset wikics --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec inner --enc gat --est jsd --readout mean --sampler gca --dataset pubmed --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec bilinear --enc gat --est jsd --readout mean --sampler gca --dataset pubmed --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 --dec inner --enc gin --est nce --readout sum --sampler node-neighbor-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 --dec bilinear --enc gin --est nce --readout sum --sampler node-neighbor-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 --dec inner --enc gat --est nce --readout sum --sampler node-rand_walk-random --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 --dec bilinear --enc gat --est nce --readout sum --sampler node-rand_walk-random --dataset cora --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec inner --enc gcn --est jsd --readout mean --sampler aug --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 --dec bilinear --enc gcn --est jsd --readout mean --sampler aug --dataset amazon_photo --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 --dec inner --enc linear --est nce --readout mean --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 --dec bilinear --enc linear --est nce --readout mean --sampler node-rand_walk-random --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec inner --enc gin --est jsd --readout mean --sampler mvgrl --dataset coauthor_cs --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 --dec bilinear --enc gin --est jsd --readout mean --sampler mvgrl --dataset coauthor_cs --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec inner --enc gin --est nce --readout mean --sampler node-neighbor-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 128 --dec bilinear --enc gin --est nce --readout mean --sampler node-neighbor-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec inner --enc gin --est jsd --readout sum --sampler aug --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --hiddens 64 64 64 --dec bilinear --enc gin --est jsd --readout sum --sampler aug --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec inner --enc gat --est nce --readout sum --sampler aug --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 64 64 64 --dec bilinear --enc gat --est nce --readout sum --sampler aug --dataset cora --model ss_gae --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 --dec inner --enc none --est jsd --readout mean --sampler gca --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 --dec bilinear --enc none --est jsd --readout mean --sampler gca --dataset amazon_computers --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc linear --est nce --readout sum --sampler node-neighbor-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 64 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc linear --est nce --readout sum --sampler node-neighbor-random --dataset coauthor_phy --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec inner --enc gin --est jsd --readout mean --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.001 --patience 3 --hiddens 128 128 128 --dec bilinear --enc gin --est jsd --readout mean --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec inner --enc gcn --est nce --readout sum --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
python3 -m openne --clf-ratio 0.2 --dim 128 --early-stopping 20 --epochs 500 --lr 0.01 --patience 3 --dec bilinear --enc gcn --est nce --readout sum --sampler node-neighbor-random --dataset amazon_photo --model ss_nodemodel --task unsupervisednodeclassification $*
