python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec inner --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec bilinear --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-neighbor-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 128 --hiddens 128 128 128 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 256 --hiddens 256 256 256 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc gin --dec mlp --sampler node-rand_walk-except_neighbor --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 512 --hiddens 512 512 512 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc linear --dec inner --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc linear --dec inner --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc linear --dec inner --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc linear --dec inner --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc linear --dec inner --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc linear --dec inner --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.02 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc linear --dec inner --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 --lr 0.03 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc linear --dec inner --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.001 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc linear --dec inner --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.01 $*
python3 -m openne --model ss_nodemodel --dataset citeseer --enc linear --dec inner --sampler node-neighbor-random --readout mean --est jsd --epochs 500 --early-stopping 20 --dim 64 --hiddens 64 64 --lr 0.03 $*
